# Generated by Django 4.2.3 on 2023-11-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('FreelanceTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(default='')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='freelancer_notification', to='account.freelancer')),
            ],
            options={
                'db_table': 'FreelancerNotification',
            },
        ),
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(default='')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hirer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hirer_notification', to='account.hirer')),
            ],
            options={
                'db_table': 'ClientNotification',
            },
        ),
    ]
