# Generated by Django 4.2.3 on 2023-11-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('FreelanceTask', '0002_freelancernotification_clientnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_hired',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_accepted', models.BooleanField(default=False)),
                ('freelancer_rejected', models.BooleanField(default=False)),
                ('project_title', models.CharField(default='', max_length=255)),
                ('hiring_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('message', models.TextField(default='')),
                ('hiring_budget_type', models.CharField(choices=[('Hourly', 'hourly'), ('Fixed', 'fixed')], default='', max_length=15)),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('hired_freelancer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hired_freelancers', to='account.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hired_projects', to='FreelanceTask.project')),
            ],
            options={
                'db_table': 'Hire',
            },
        ),
    ]
